# Spring properties
spring:
  application:
    name: api-gateway  # Identify this application

# Server
server:
  port: 8081   # HTTP (Tomcat) port

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 5   # DO NOT DO THIS IN PRODUCTION

# Api-Gate-Way
zuul:
  prefix: /api
  routes:
    auth-service:
      path: /auth-service/**
      serviceId: AUTH-SERVICE
      sensitiveHeaders: Cookie,Set-Cookie
      
    todo:
      path: /todo/**
      serviceId: TODO
      sensitiveHeaders: Cookie,Set-Cookie
    web-crawler:
      path: /webcrawler/**
      serviceId: WEB-CRAWLER
      sensitiveHeaders: Cookie,Set-Cookie  
      
      
# Increase the Hystrix timeout to 60s (globally)
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
      
